package hr.cnzd.dsi2021.Model;

import java.util.ArrayList;
import java.util.List;

public class PitanjaStariji {

    public static List<KvizPitanje> napuniPitanja(){

        List<KvizPitanje> pitanja = new ArrayList<>();

        KvizPitanje p;
        KvizOdgovor o;

        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Što je phishing ili mrežna krađa identiteta?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Kradljivac podataka žrtvi šalje mail s lažnim linkom gdje se žrtva mora prijaviti sa svojim podacima za taj server");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Kradljivac podataka žrtvine podatke krade bez da žrtva sudjeluje");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Žrtvi su ugroženi svi podaci na računalu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Kradljivac ukrade žrtvi osobnu iskaznicu");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Što je grooming?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Uspostavljanje povjerenja i emocionalne povezanosti između djeteta i odrasle osobe komunikacijskom tehnologijom, s ciljem vrbovanja i iskorištavanja maloljetnika u seksualne svrhe");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Krađa identiteta putem društvenih mreža");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Krađa podataka s računala žrtve");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Krađa kontakata s mobitela");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Kome možete prijaviti nasilje putem interneta?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Bilo kojoj odrasloj osobi u koju imate povjerenja");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Svom prijatelju/prijateljici");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Strancu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nikome");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Posljedice elektroničkog nasilja mogu uključivati?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Sve navedeno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Promjene raspoloženja");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Probleme sa spavanjem");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Neobjašnjivu bol u trbuhu");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Podatak s interneta se može obrisati trajno?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Netočno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Točno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Oboje");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nijedno");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Što je broj 0800 606 606?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Besplatna savjetodavna linija Centra za sigurniji internet");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Informativni broj policije");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Služba za korisnike Samsung uređaja");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Izmišljen broj");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Hotline online prijavni obrazac Centra za sigurniji internet (www.csi.hr) omogućava da anonimno prijavimo slučajeve govora mržnje na internetu?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Tocno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Netocno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Oboje");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nijedno");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Na koji način trebamo reagirati na nasilje putem interneta?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Obavijestiti roditelje ili neku drugu odraslu osobu od povjerenja");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ne treba reagirati kako ne bi i sam postao/la žrtva");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Dovoljno je reći prijatelju/prijateljici");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ne može se reagirati");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Trollanje je pisanje s primarnim ciljem da se od sugovornika isprovocira emotivna reakcija ili da se na drugi način ometa normalna rasprava na temi.");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Tocno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Netocno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Oboje");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nijedno");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Uzimanje tuđeg identiteta i slanje poruka i drugih sadržaja u tuđe ime smatra se elektroničkim nasiljem?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Tocno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Netocno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Oboje");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nijedno");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Izazivanje i snimanje tučnjave ili drugih nasilnih sadržaja te njihovo širenje ne smatra se elektroničkim nasiljem?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Netocno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Tocno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Oboje");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nijedno");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Stavljanje slike lica osobe na nepoznato golo tijelo i dijeljenje te slike smatra se elektroničkim nasiljem?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Tocno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Netocno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Oboje");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nijedno");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Koji znakovi mogu ukazivati na to da je vaš prijatelj/prijateljica žrtva elektroničkog nasilja?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Sve od navedenog");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Povlačenje od prijatelja i aktivnosti  kojima je prije uživao/uživala");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Prestanak korištenja računala ili mobitela");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Brisanje korisničkih računa ili otvaranje puno novih računa");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Na koji način možete prijaviti neprimjeren/šteta ili ilegalan sadržaj na internetu?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Anonimnom prijavom na  https://www.csi.hr  ili na https://redbutton.mup.hr/");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Isključivo poštom");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Isključivo osobnim odlaskom u policijsku postaju");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Navedeni sadržaj se ne može prijaviti");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Kakav oblik ključa (lozinke) je najbolji za zaštitu?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Ključ koji ne sadrži osobne podatke, a uključuje kombinaciju malih i velikih slova, brojeva i znakova");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ime kućnog ljubimca ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Datum rođenja ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Prezime");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Koji je oblik lozinke najteži za pogoditi?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Lozinka koja sadrži 10 znakova, mješavina raznih velikih i malih slova, brojki i interpunkcijskih znakova ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ime prve simpatije ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("12345678 ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Djevojačko prezime majke");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Kako prepoznati da je računalo zarađeno virusom?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Na računalu se pojavljuju čudni i alarmantni upiti, umjesto stranica koje inače posjećujemo pojavljuju se web trgovine i oglašivački sadržaji");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Računalo odjednom radi bolje nego prije i manje se grije ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Računala ne mogu biti zaražena malverom");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ne može se prepoznati");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Koji su podaci, prema pravilima privatnosti koje definira Facebook, uvijek javno dostupni?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Ime, prezime i fotografija profila ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Djevojačko prezime majke ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ime našeg omiljenog glumca iz serije ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Mjesto i datum rođenja");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Lažna informacija koja se lančano širi naziva se:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Hoax ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Smicalica ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Pero ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Server");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Koje su postavke privatnosti na Facebooku moguće?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Javno, prijatelji, prijatelji osim, samo ja, određeni prijatelji i prilagođeno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Javno i privatno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Postavke mogu biti samo javne");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Na mom Facebook profilu moje objave mogu vidjeti samo prijatelji");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Internet predatori su:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Osobe koje koriste internet kao sredstvo upoznavanja s djecom, radi uspostavljanja komunikacije i odnosa, s ciljem da tu djecu seksualno uznemiravaju i zlostavljaju");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Osobe koje s Interneta preuzimaju ilegalan software");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Drugi naziv za njih je Hakeri");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Internet predatori ne postoje");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Internet predator najčešće:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Ima lažan profil, pretvara se da je tvoj vršnjak ili poznanik, postavlja mnogo pitanja i želi se približiti sa zlom namjerom");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Koristi društvene mreže s nazivom profila Internet predator");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ne postoji internet predator");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Pretvara se da je lik iz crtića");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Objavljivanje fotografija ili video zapisa bez pristanka drugih osoba koje se nalaze na fotografiji ili videu:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Nije dozvoljeno bez izričitog dopuštenja te osobe");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Možemo objaviti video ili fotografiju ako nam je lijepa");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Možemo objaviti fotografiju ili video, ali samo na Instagramu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nije dozvoljeno ako ne stavimo filtere");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Poklone, skinove, zlato ili druge nagrade i poklone u igrama i na internetu:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Ne smijem prihvaćati od nepoznatih osoba s interneta");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Mogu prihvatiti jedino ako uzvratim istim poklonom");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Proslijedit ću poklon svojim prijateljima");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Prihvatit ću poklon bez pitanja");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Centru za sigurniji Internet se možeš obratiti ukoliko:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Pronađeš neželjen sadržaj online ili sumnjaš u nasilje na internetu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ne znaš svoju lozinku za Facebook");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Izgubio si mobitel");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ne znaš kako utipkati bon za mobitel");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Kome je potrebno razvijanje medijske pismenosti?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Djeci, mladima i odraslima");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Kućanskim aparatima");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Mobilnim uređajima");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Samo starim ljudima");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Što od navedenog ne trebaš raditi kako bi spriječio nasilje putem interneta?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Uzvratiti istom mjerom i pokazati tko je glavni");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Obavijestiti roditelje ili školskog pedagoga/psihologa");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Razgovarati sa žrtvom, savjetovati da ne odgovara na bilo kakve sumnjive poruke");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Prijaviti slučaj administratoru internetske stranice");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Što je to zloćudan kod (eng. malicious software)?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Kompjuterski program kojemu je cilj naštetiti kompjuterskom sistemu na kojem je pokrenut");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Program koji ne zna što radi");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ne postoji zloćudan kod");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Dobar duh kompjutera");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Kada napadač šifrira korisnikove podatke i traži otkupninu u zamjenu za ključ za dešifriranje, govorimo o:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Ransomware");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Teksaškom obračunu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Viteškom dvoboju");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Piratskim otmicama");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Dok se kompjuterski virus širi unutar jednog kompjutera, kompjuterski crv se širi:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Između više kompjutera mrežom");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Po dvorištu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Po kući");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("U kupusu");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Po čemu se mogu prepoznati trojanski konji?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Predstavljaju se kao korisni programi, ali su zapravo zloćudan kod");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Računala zaražena trojanskim konjem mogu jahati po internetu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Po tome što izgledaju kao konji");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nemoguće ih je prepoznati");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Program kojemu je cilj nadzor, tj. špijuniranje korisnika naziva se:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Spyware");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Tajni agent");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ninja");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("James Bond");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Koja je dobna granica za registraciju na medijima kao što su Facebook, Instagram i Youtube?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("13 godina");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("21 godina");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("16 godina");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("18 godina");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("IP je kratica za:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Internet Protocol");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ivica i Perica");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Imaginarni prijatelj");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Internet pas");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Svoje aplikacije možemo zaštititi:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Programom za zaštitu protiv virusa i zloćudnih programa");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Otkrivanjem svojih osobnih podataka na internetu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Otvaranjem sumnjivih e-mail priloga");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Instaliranjem raznih programa sa sumnjivih stranica");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Kako spriječiti trajno gubljenje podataka u slučaju napada?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Kontinuirano održavanje jedne ili više sigurnosnih kopija barem najbitnijih podataka");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Držati podatke u banci");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Čuvati podatke ispod madraca");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Kremom protiv gubljenja podataka");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Koja je svrha vatrozida (firewall)?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Služi kao prepreka između poznate i nepoznate mreže te dopušta ili zabranjuje promet između njih");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Da zapali zidove oko kompjutera");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Da se napadaču zapali kompjuter");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Da ugrije sobu");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Programi koji mogu prepoznati zloćudne programe i zaustaviti njihove aktivnosti nazivaju se:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Antivirusni programi, Antispyware programi, Antimalware programi");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Microsoft Word");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Program za crtanje Paint");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Kalkulator");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Za geografski udaljene korisnike, sigurnu komunikaciju s mrežom omogućit će:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("VPN, virtualna privatna mreža");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Planinska mreža");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Vulkanska mreža");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Susjedova mreža");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Dobio/la si email u kojemu te netko traži osobne podatke. Što učiniti?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Nikada nemoj davati svoje osobne podatke, pogotovo ne na email zahtjeve stranaca");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Poslati fotografiju osobnih podataka (npr. Osobne iskaznice)");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Pitati ih prvo za njihove osobne podatke");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Poslati osobne podatke");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Prijatelj je ostao prijavljen na društvenoj mreži na javnom školskom računalu. Što učiniti?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Odjaviti ga, javiti mu i preporučiti promjenu lozinke");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Javljati se drugim osobama s njegovog profila");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Objaviti podrugljive poruke");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Samostalno izmijeniti lozinku i onemogućiti mu korištenje profila");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Zašto odmah možemo zaključiti da se kod emailova arapskih prinčeva i dobitaka na lutriji radi o phishingu?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Traže da primatelj emaila pošalje svoje osobne podatke na adresu pošiljatelja i često sadrže rečenice loše prevedene na engleski jezik.");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ne radi se o phishingu, stvarno smo dobili na lutriji");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ne znamo dok ne probamo");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Radi se o velikim novcima, vrijedi riskirati");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Napadači svojim programima ciljaju na sljedeće podatke svojih žrtava:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Ime korisnika, broj kreditnih kartica, lozinke s kojima se mogu prijaviti kao korisnik");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ime kućnog ljubimca, veličina patika");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Korisnikove hobije");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Korisnikovu omiljenu boju");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Igrajući igricu s drugim ljudima, jedna osoba vas počne vrijeđati. Što učiniti?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Ostati smiren i pitati što je izazvalo uzrujanost; ako je osoba nerazumna, napustiti igru i izbjeći dodatno provociranje; prijaviti osobu vlasnicima igre");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Provocirati osobu kako ne zna igrati");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Hvaliti se kako ste bolji u igri od te osobe");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Uzvratiti istom ili većom mjerom");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Kako bi izbjegli situaciju da nam sigurnosne kopije podataka sadrže virus, trebamo:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Prije arhiviranja i snimanja sigurnosne kopije sadržaj provjeriti antivirusnim programom");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Sadržaj staviti na USB, pa s USB-a na drugo računalo");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Sadržaj staviti na CD pa ga obrisati vlažnim maramicama");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ne smiju se raditi sigurnosne kopije");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Je li preporučljivo automatsko ažuriranje operativnog sustava?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Da, kako bi se smanjila mogućnost zaraze kompjutera malverom");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nije, automatsko ažuriranje ne valja");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ažurirati se može samo manualno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ne treba ažurirati operativni sustav");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Socijalnim inženjeringom manipulira se:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Ljudima");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Mobitelima");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Vatrom i ledom");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Vjevericama");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Zašto se ne preporučuje plaćanje otkupnine autorima ransomware-a?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Time financiramo kriminalne skupine i ne sprječavamo ih da nas ili druge opet napadnu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Novce treba štedjeti");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Novci mogu pokupiti virus");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Za te novce se može kupiti novi kompjuter");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Što ne spada u društvene medije?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Malware");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Instagram");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Facebook");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Twitter");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Bežična mreža je dobra ukoliko koristimo:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("WPA, WPA2 i WPA3 standarde enkripcije");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("mp3");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("mp4");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Bežična mreža nije nikad dobra");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Internet kupovinu treba obavljati:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Samo na provjerenim kompjuterima");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("S javnog kompjutera u kafiću");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Sa zaraženog kompjutera");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("S pozivom internet poslužitelju da im kažete popis stvari koje vam treba kupiti");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Netko me ucjenjuje s osjetljivim fotografijama, što učiniti?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Obratiti se roditeljima, nastavnicima ili Centru za sigurni internet kako bi pomogli");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Platiti da prestane ucjenjivanje");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ignorirati ucjenu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Prijetiti ucjenjivaču da ste profesionalni haker");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Koja se od navedenih lozinki čini najsigurnijom?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("$1gurn@L0z1NKa");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("sigurnalozinka");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("12345");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("teskalozinka1");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Upoznao/la si novu osobu preko interneta. Što treba uzeti u obzir kod izmjenjivanja privatnih podataka?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Moguće je da se osoba lažno predstavlja i treba izbjeći davanje osjetljivih podataka dok niste sigurni u identitet druge osobe");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Osoba se potrudila upoznati te i ne moraš se brinuti oko sigurnosti svojih podataka");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Prvo izmijeniti fotografije, a onda ostale podatke");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nema razloga da se neko lažno predstavlja");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Smijem li pristupati svim sadržajima na internetu?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Ne, postoje mjesta na internetu koja su neprimjerena ili opasna ili mogu naštetiti mom kompjuteru");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ako mogu drugi, mogu i ja");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ako se nešto dogodi, ugasit ću kompjuter");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Da, nema razloga za brigu");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Što su to mikro transakcije?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Mikro transakcije se najčešće vežu uz igrice gdje za relativno mali iznos možete kupiti određene stvari unutar igre");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Kada banke posluju s kovanicama");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Kupovina sitnih stvari poput žvakaćih guma");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Transakcija između sitnih bića poput mrava");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Mogu li mikro transakcije napraviti stvarne troškove s obzirom na to da se radi o malim iznosima?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Da, mogu stvoriti ozbiljne troškove jer cilj proizvođača je malim cijenama natjerati na kontinuirano kupovanje");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ne, radi se o malim iznosima za koje se uvijek ima novac");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ne, a i da može samo je bitno napredovati u igri");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ovisi od igre do igre");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Kojim aplikacijama na kompjuteru trebamo dati dozvolu za izvršavanje?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Samo onim koje smo željeli pokrenuti i za koje znamo što rade");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Sumnjivim aplikacijama čudnih imena");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Svim aplikacijama za koje iskoči upit");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nijednoj aplikaciji");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Znamo osobu koja je napravila profil u ime neke poznate osobe i predstavlja se kao ta osoba. Što učiniti?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Obavijestiti odraslu osobu i prijaviti lažni profil");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Javiti se lažnom profilu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Dobra ideja, također napraviti profil u ime neke poznate osobe i malo se zabaviti");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ništa, nije vaš problem");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Kako povećati sigurnost pri korištenju mobilnih telefona?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Upotrijebiti iste mjere opreza kao i na kompjuteru");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Mobilni telefoni su potpuno druga priča od kompjutera, nije potrebna zaštita");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Koristiti maske za zaštitu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Sigurnost mobilnog telefona je uključena u cijenu mobilne tarife");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje

        return pitanja;
    }
}

