package hr.cnzd.dsi2021.Model;

import java.util.ArrayList;
import java.util.List;

public class PitanjaMladi {

    public static List<KvizPitanje> napuniPitanja(){

        List<KvizPitanje> pitanja = new ArrayList<>();

        KvizPitanje p;
        KvizOdgovor o;

        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Pojam „malware“ skraćenica je za:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Malicious software");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Mailable software");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Magic software");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Master software");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Kako se najlakše može prepoznati postojanje zloćudnog koda (malicious software) na računalu?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Usporavanje računala i pojava različitih poteškoća prilikom rada");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Pravilno izvođenje zadanih naredbi");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ubrzani rad računala");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Redovito ažuriranje računala");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Što označava „https://“ na početku URL-a u odnosu na „http://“ ?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Informacije unesene u stranicu su enkriptirane");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Dostupna je najnovija verzija stranice");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Stranica je u visokoj rezoluciji");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Stranica je nedostupna");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Što označava skraćenica VPN?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Virtual Private Network");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Virtual Personal Network");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Visual Processing Network");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Visual Public Note");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Što ne skriva VPN?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Kolačiće");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Mrežnu aktivnost");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Mrežnu lokaciju");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Povijest pregledavanja");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Koja je funkcija VPN-a?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Enkripcija podataka");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Promjena IP adrese");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Prijenos datoteka");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Online kupovina");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Što od navedenog nije primjer cyber bullying-a?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Čestitati nekome rođendan");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Lažno predstavljanje i slanje neugodnih poruka");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Slanje uvredljivih poruka i prijetnji");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Širenje laži ili objavljivanje fotografija s ciljem sramoćenja nekog na društvenim mrežama");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Čije bi zahtjeve na društvenim mrežama trebao prihvaćati?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Isključivo ljude koje znam");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Prijatelje prijatelja");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Bilo koga");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Svakoga tko se čini poznatim");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Što omogućava zaštitu individualnog računalnog sustava?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Desktop Firewall");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Firewall");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Malware");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Virus");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Kako se naziva programski kod koji se uvrštava u softver računala s ciljem poboljšanja sigurnosti i osiguravanja dobre funkcionalnosti sustava?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Patch");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Spyware");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Desktop");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Antivirusni program");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Što od navedenog nije simptom spyware-a na računalu?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Nefunkcionalnost tipkovnice");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nemogućnost pristupa internetu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Vidljive promjene na zadanom pregledniku");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Pojava dijaloških okvira na računalu");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Zloćudan softver koji prikuplja informacije o korisnicima bez njihovog znanja naziva se?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Spyware");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Trojanski konj");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Virus");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Adware");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Spyware lako zarazi računalo te je stoga izrazito težak za:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Identificirati");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Obrisati");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Kopirati");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ažurirati");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Koliko znakova treba sadržavati lozinka?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Koliko god je moguće");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("7");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("12");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nije bitno");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Što od navedenog nije cyber napad?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Hardware");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Malware");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Phishing");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Spyware");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Što trebaš napraviti kako bi zapamtio dugačku lozinku?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Koristiti mnemoniku/asocijacije");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Reći prijatelju");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Podijeliti na Facebook-u");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Tetovirati");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Kako najbolje uspješno promijeniti lozinku?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Koristiti nešto što možeš lako zapamtiti, ali modificirati uz nekakav pamtljiv uzorak");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Upotrijebiti nešto brzo i lako za upisati tako da te nitko ne može vidjeti");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Koristiti osobni podatak");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Dodati broj ili znak na kraj stare lozinke");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Neželjeni program koji automatski prikazuje ili preuzima oglase na računalo naziva se:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Adware");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Hardware");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Software");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Spyware");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Što od navedenog nije oblik zloćudnog softvera?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Laptop");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Virus");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Botnet");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Trojanski konj");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Zloćudni softver koji uskraćuje korisnicima pristup računalnim resursima te zahtijeva plaćanje otkupnine kako bi se to ograničenje ukinulo naziva se:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Ransomware");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Spyware");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Adware");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Hardware");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje

        return pitanja;
    }

}
