package hr.cnzd.dsi2021.Model;

import java.util.ArrayList;
import java.util.List;

public class PitanjaStariji {

    public static List<KvizPitanje> napuniPitanja(){

        List<KvizPitanje> pitanja = new ArrayList<>();

        KvizPitanje p;
        KvizOdgovor o;

        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Što od navedenog trebaš napraviti kako bi spriječio nepoznatim korisnicima pristup mreži?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Promijeniti zadani WEP ili WPA pristupni ključ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ažurirati postavke sigurnosti");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Maknuti računalo s mreže");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ugasiti računalo");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Koji je najbolji način za dijeljenje osjetljivih informacija na nesigurnoj mreži?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Upotrebom enkriptiranog formata");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Kao privitak u e-mailu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Dijeljenjem preko društvenih mreža");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Upotrebom komprimiranog formata");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Što od navedenog može uzrokovati pojavu zloćudnog programa ili softvera?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Upotreba nepoznatog USB diska za prijenos podataka");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Redovito ažuriranje anti-virusnih programa");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Otvaranje provjerenih datoteka");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Upotreba provjerenog softvera");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Zašto je potrebno zaključati računalo nakon njegovog korištenja?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Radi sprječavanja neovlaštenog pristupa podacima");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Radi uštede struje");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Radi osiguravanja funkcionalnosti računala");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Radi bržeg ažuriranja operativnog sustava");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Za zaštitu komunikacije prilikom upotrebe javne mreže trebaš napraviti sljedeće:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Koristiti VPN");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Priključiti se na mrežu sa najjačim WiFi signalom");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ponovno pokrenuti računalo");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Isključiti lokaciju");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Kako možeš znati da stranica enkriptira svoj promet?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Prikazanim lokotom u području URL-a stranice");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Sve stranice enkriptiraju svoj promet");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Duže se učitava");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Provjerom na Google-u");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Što od navedenog nije način na koji operativni sustav računala može poboljšati sigurnost računala?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Skeniranjem lica korisnika");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Osiguravanjem različitih razina pristupa");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Pružanjem usluge zaštite lozinke");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ažuriranjem softvera");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Koja je glavna funkcija vatrozida (firewall)?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Ograničavanje mrežnog prometa između računala i Internet mreže s ciljem zaštite od zloćudnih programa i virusa");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Sigurnost od požara");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Sprječavanje pregrijavanja računala");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Grijanje radnog prostora");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("U kojem se programu nalazi vatrozid?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Windows Defender Antivirus");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("PC protect");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Total AV");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Malware");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Što je hakiranje?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Pronalaženje slabosti na računalu ili mreži s ciljem njihovog iskorištavanja i osiguravanja pristupa");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Poznavanje vlastite lozinke");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Mogućnost pristupa Internetu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Upotreba kodova u video-igri");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Izazivanje i snimanje tučnjave ili drugih nasilnih sadržaja te njihovo širenje ne smatra se elektroničkim nasiljem?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Sve od navedenog");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Korištenjem dugačkih i složenih lozinki");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Preuzimanjem aplikacija sa provjerenih i pouzdanih platformi");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Instalacijom anti-malware programa na svoje računalo");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Vrsta programera koji neovlašteno pristupa tuđem računalu naziva se:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Haker");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Front-end developer");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Računalni programer");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Grafički dizajner");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Tehnologija i praksa razvijena za zaštitu sustava i uređaja od neovlaštenog pristupa, napada ili štete naziva se:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Cyber security");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Web development");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Malware");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Information Technology");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Koji su glavni znakovi krađe identiteta?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Sve od navedenog");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Dijeljenje sadržaja na društvenim mrežama kojeg nisi podijelio");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nemogućnost pristupa bankovnom računu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Primanje e-maila o aktivnosti koju nisi učinio");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Zašto je važno što ranije prijaviti krađu identiteta?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Kradljivac identiteta inače ima više vremena za prijevaru i stvaranje dodatnih problema");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Svaki pojedinac ima raspon od 7 dana za prijavu jer u suprotnom trebaju razviti novi identitet");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Naknadna prijava se plaća");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Dobiješ poklon");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Koji oblik osobne informacije prevaranti uglavnom neće upotrijebiti prilikom krađe identiteta?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Broj mobitela");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Broj kreditne kartice");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Broj bankovnog računa");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Broj vozačke dozvole");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Ako tvoje računalo ne radi kako spada, koji oblik sigurnosne prijetnje može biti u pitanju?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Malware");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Krađa identiteta");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Phishing");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Spam");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Što od navedenog nije oblik socijalnog inžinjeringa?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Hakiranje");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Phishing");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Scareware");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Baiting");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Kriminalna aktivnost koja  se odnosi na slanje lažnih poruka korisnicima s ciljem prikupljanja njihovih povjerljivih podataka naziva se:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Phishing");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Spyware");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Krađa identiteta");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Hakiranje");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Što od navedenog nije obilježje „phishinga“?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Poruka u pozitivnom tonu poslana sa provjerene adrese");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Poruka napisana s ciljem stvaranja panike ili uznemirenja");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Zahtijevanje odlaska na ponuđeni link ili otvaranje privitaka");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Traženje osjetljivih podataka");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Socijalni inžinjering iskorištava koju sigurnosnu manu računalnog sustava?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Korisnika");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Računalo");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Lozinku");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Mrežu");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Na koji račun trebaš postaviti najsigurniju lozinku?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Primarni e-mail račun");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Bankovni račun");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Račune društvenih mreža");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Školska e-mail adresa");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Što trebaš napraviti ukoliko dobiješ „phishing“ mail?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Obrisati ga");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Kliknuti poslani link");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Odgovoriti na njega");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Kontaktirati banku");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Zašto je važno redovito ažurirati anti-virusni softver na računalu?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Kako bi softver mogao zaštititi računalo od svih virusa");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Kako bi softver prepoznao stare viruse");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Kako bi se popunila prazna memorija računala");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Kako bi se računalo zaštitilo od neželjenih mailova");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Što od navedenog može „zaraziti“ druge programe unoseći u njih kopiju samog sebe?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Virus");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Trojanski konj");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Računalni crv");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Spam");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Što od navedenog nije cyber zločin?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Pristupanje Dark Web-u");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Upotreba tuđeg računala bez dozvole");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Kreiranje korisničkog računa na platformi iako si ispod dobne granice za pristup takvom sadržaju");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nasamariti nekoga na instaliranje malware-a");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Koja od navedenih poruka je primjer „phishinga“?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Sve od navedenog");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("„You won a new phone, click here to claim it.“");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("„Help! I am stuck in a foreign country and I need some money to get back home.“");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("„Your bank account has been hacked. Login here to protect yourself.“");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Koja se od navedenih lozinki čini najnesigurnijom?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Lozinka");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("!Aa,lasw#");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("*LooneyTunes33");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ilovecats!#95");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Što trebaš napraviti ukoliko sumnjaš da si hakiran?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Sve od navedenog");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Prijaviti problem");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Promijeniti lozinku");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Reći roditeljima ili odgovornoj odrasloj osobi");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Kako izbjeći ili umanjiti rizik od malware napada?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Upotrebom operativnog sustava Linux zbog manje baze korisnika");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Preuzimanjem piratskih filmova sa Interneta");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Otvaranjem nepoznatih e-mailova");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Neažuriranjem operativnog sustava vlastitog računala");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Što od navedenog nije primjer dobre prakse kada je u pitanju zaštita računa na društvenim mrežama?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Zapisati lozinke na desktop računala");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Jaka lozinka");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Povezivanje računa s brojem mobitela radi veće sigurnosti");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Log-out nakon završetka korištenja");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Kako se naziva vrsta ekstenzije za preglednik koja onemogućava društvenim mrežama da prati mrežnu aktivnost korisnika?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Blur");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Fader");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ad-blocker");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Adware");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Što stranice koriste kako bi verificirale korisnike i spriječile napade botova?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("CAPCHA");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Kolačići");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Bookmarks");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ad-blocker");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Što trebaš napraviti kako bi ograničio pristup svojim uređajima i datotekama?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Koristiti tzv. „multi-factor“ autentikaciju");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Omogućiti pristup podacima putem otvorene WiFi mreže");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Podijeliti lozinke sa najboljim prijateljima");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ažurirati software jednom godišnje");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Koji je najbolji način za zaštitu vlastitog routera?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Sve od navedenog");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Log-out kao administrator kada je router postavljen");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Isključiti daljinsko upravljanje");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Promijeniti postavljenu lozinku i naziv koji se nalazi na routeru");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Kako kriminalci započinju svoje ransomware napade?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Sve od navedenog");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Provaljivanjem u server i instaliranjem malware-a");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Korištenjem stranica koje automatski instaliraju zloćudne programe na računalo");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Slanjem sumnjivih mailova");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Ukoliko se želiš pribilježiti na pretplatničku listu i primati novosti od neke stranice, koje podatke jedino trebaš podijeliti?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Ime i e-mail adresu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ništa");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Broj kreditne kartice, puno ime i adresu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Puno ime, adresu stanovanja, broj mobitela i e-mail adresu");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Kako se virus ne može širiti i zaraziti računalo?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Antivirusnim programom");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("USB");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("E-mail");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Putem zaraženih stranica");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Koje osobne podatke društvene mreže i aplikacije mogu prikupljati?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Sve od navedenog");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Jezične preference");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Uređaj koji koristiš");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Lokaciju");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Koja je razlika između virusa i računalnog crva?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Računalni crv se širi samostalno, a virus se mora vezati uz drugi program");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Virus može zaraziti tzv. „boot sektor“, a crv ne može");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Računalni crv se širi samostalno dok virus treba biti postavljen kao privitak u e-mailu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Virus je napisan u C++, a računalni crv nije");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Što sve obuhvaćaju osobni podaci?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Sve od navedenog");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Povijest obrazovanja");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Puno ime i datum rođenja");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Novčana primanja");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Kako ukloniti Trojanskog konja sa računalnog sustava?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Kupnjom komercijalnih rješenja za uklanjanje Trojanskog konja");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Deinstaliranjem i ponovnim instaliranjem svih aplikacija");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ponovnim pokretanjem cjelokupnog sustava");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Pretraživanjem Interneta");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Koliko često se preporuča mijenjati lozinke?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Svakih mjesec dana");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Svaka dva tjedna");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Svakih tjedan dana");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Svaki dan");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Koja metoda hakiranja bilježi sve tvoje pritiske tipki na tipkovnici računala?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Keylogging");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Keyjacking");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Keyhijacking");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Keyboard monitoring");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Dio stranice koji omogućava stranici da vlastite prikupljene informacije o korisniku pohranjuje na njegovo računalo naziva se:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Kolačići");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Spam");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Malware");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Adware");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Koliko često trebaš praviti back-up računala?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Svaki put kada kreiraš nove datoteke ili postaviš slike koje ne želiš izgubiti");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Jednom tjedno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Kada sumnjaš da je u pitanju nekakav problem");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Svaki dan");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Ukoliko ne možeš obrisati datoteku inficiranu malware-om, koju metodu možeš prvu upotrijebiti?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Pokrenuti Windows Safe Mode te zatim pokušati obrisati datoteku");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Pokrenuti Windows Defender");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Pokrenuti Windows Repair");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Formatirati postojeću datoteku te ju zatim probati obrisati");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Koji tipovi datoteka mogu biti zaraženi virusom?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Pdf, doc, xsl");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Virusi ne mogu zaraziti datoteke");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Jpg i png");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ppt");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Kako bi se zaštitio od virusa bitno je koristiti koji od navedenih preglednika?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Nije bitno koji se preglednik koristi");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Internet Explorer");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Google Chrome");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Mozilla Firefox");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje
        p = new KvizPitanje();
        p.setVrsta("stariji");
        p.setTekst("Koju standardnu enkripciju ne treba koristiti zbog sigurnosnih propusta?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("WEP");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("WPA2");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Oboje");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Sigurnosni propusti ne postoje");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo KvizPitanje

        return pitanja;
    }
}

