package hr.cnzd.dsi2021.Model;

import java.util.ArrayList;
import java.util.List;

public class PitanjaMladi {

    public static List<KvizPitanje> napuniPitanja(){

        List<KvizPitanje> pitanja = new ArrayList<>();

        KvizPitanje p;
        KvizOdgovor o;

        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Što nam može pomoći u prepoznavanju lažnog profila na društvenim mrežama?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Sve od navedenog");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Provjera prijatelja i pratitelja");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Provjera vremenske linije objava na društvenim mrežama");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Provjera ima li osoba profilnu fotografiju, koliko ima ostalih fotografija i kakve su one");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Tko osim vas treba znati vašu lozinku?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Samo roditelji");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Samo najbolji prijatelj/prijateljica");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Isključivo dečko/djevojka");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nitko");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Posljedice elektroničkog nasilja mogu uključivati?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Sve navedeno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Depresiju");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Probleme sa spavanjem");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Gubitak apetita");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Koji sadržaj od navedenih nije primjeren za objavu na društvenim mrežama?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Uvredljive poruke i fotografije");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Videozapisi s rođendana");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Obiteljske fotografije");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Fotografije s prijateljima");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Podatak s interneta se može obrisati trajno?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Netočno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Točno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Oboje");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nijedno");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("www.sini.hr je platforma Centra za sigurniji internet na kojem su dostupni sadržaji o sigurnosti na internetu namijenjeni djeci, mladima, roditeljima i stručnjacima?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Točno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Netočno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Oboje");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nijedno");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Hotline online prijavni obrazac Centra za sigurniji internet (www.csi.hr) omogućava da anonimno prijavimo slučajeve govora mržnje na internetu?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Točno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Netočno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Oboje");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nijedno");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Uzimanje tuđeg identiteta i slanje poruka i drugih sadržaja u tuđe ime smatra se elektroničkim nasiljem?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Točno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Netočno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Oboje");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nijedno");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Izazivanje i snimanje tučnjave ili drugih nasilnih sadržaja te njihovo širenje ne smatra se elektroničkim nasiljem?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Netočno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Točno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Oboje");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nijedno");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Posljedice nasilja putem interneta katkad mogu biti opasnije od onih prouzročenih međuvršnjačkim nasiljem u svakodnevnim situacijama?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Točno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Netočno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Oboje");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nijedno");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Što je broj 0800 606 606?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Besplatna savjetodavna linija Centra za sigurniji internet");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Informativni broj policije");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Služba za korisnike Samsung uređaja");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Izmišljen broj");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Na koji način trebamo reagirati na nasilje putem interneta?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Obavijestiti roditelje ili neku drugu odraslu osobu od povjerenja");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ne treba reagirati kako ne bi i sam postao/la žrtva");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Dovoljno je reći prijatelju/prijateljici");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ignorirati");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Što napraviti kada nam nepoznata osoba pošalje zahtjev za prijateljstvo na društvenim mrežama?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Prije donošenja odluke provjeriti njezin profil");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Odmah prihvatiti");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Odmah odbiti");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ovisi o igricama koje igra");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Koji znakovi mogu ukazivati na to da je vaš prijatelj/prijateljica žrtva elektroničkog nasilja?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Sve od navedenog");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Brisanje korisničkih računa ili otvaranje puno novih računa");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Povlačenje od prijatelja i aktivnosti  kojima je prije uživao/uživala");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Prestanak korištenja računala ili mobitela");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Na koji način možete prijaviti neprimjeren/šteta ili ilegalan sadržaj na internetu?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Anonimnom prijavom na  https://www.csi.hr  ili na https://redbutton.mup.hr/");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Isključivo osobnim odlaskom u policijsku postaju");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Navedeni sadržaj se ne može prijaviti");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Isključivo poštom");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Spajanjem na Internet računalo postaje:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Dostupno svim drugim računalima na Internetu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Sporije ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Skriveno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Brže ");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Kakav oblik ključa (lozinke) je najbolji za zaštitu?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Ključ koji ne sadrži osobne podatke, a uključuje kombinaciju malih i velikih slova, brojeva i znakova");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Datum rođenja ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Prezime");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ime kućnog ljubimca");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Koji je oblik lozinke najteži za pogoditi?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Lozinka koja sadrži 10 znakova, mješavina raznih velikih i malih slova, brojki i interpunkcijskih znakova ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ime prve simpatije ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("12345678");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Djevojačko prezime majke");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Kako prepoznati da je računalo zarađeno virusom?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Na računalu se pojavljuju čudni i alarmantni upiti, umjesto stranica koje inače posjećujemo pojavljuju se web trgovine i oglašivački sadržaji ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Računalo odjednom radi bolje nego prije i manje se grije ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Računala ne mogu biti zaražena malverom");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ne može se prepoznati");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Koju od navedenih informacija nije preporučljivo dijeliti na društvenim mrežama?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Adresu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Zanimljive činjenice o salati");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Vremenska prognoza ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Rezultat utakmice ");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Koji su podaci, prema pravilima privatnosti koje definira Facebook, uvijek javno dostupni?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Ime, prezime i fotografija profila ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Djevojačko prezime majke ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ime našeg omiljenog glumca iz serije ");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Mjesto i datum rođenja");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Koje su postavke privatnosti na Facebooku moguće?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Javno, prijatelji, prijatelji osim, samo ja, određeni prijatelji i prilagođeno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Postavke mogu biti samo javne");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Na mom Facebook profilu moje objave mogu vidjeti samo prijatelji");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Javno i privatno");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Internet predatori su:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Osobe koje koriste internet kao sredstvo upoznavanja s djecom, radi uspostavljanja komunikacije i odnosa, s ciljem da tu djecu seksualno uznemiravaju i zlostavljaju");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Osobe koje s Interneta preuzimaju ilegalan software");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Drugi naziv za njih je Hakeri");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Internet predatori ne postoje");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Objavljivanje fotografija ili video zapisa bez pristanka drugih osoba koje se nalaze na fotografiji ili videu:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Nije dozvoljeno bez izričitog dopuštenja te osobe");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Možemo objaviti video ili fotografiju ako nam je lijepa");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Možemo objaviti fotografiju ili video, ali samo na Instagramu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nije dozvoljeno ako ne stavimo filtere");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Poklone, skinove, zlato ili druge nagrade i poklone u igrama i na internetu:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Ne smijem prihvaćati od nepoznatih osoba s interneta");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Mogu prihvatiti jedino ako uzvratim istim poklonom");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Proslijedit ću poklon svojim prijateljima");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Prihvatit ću poklon bez pitanja");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Prijavio/la si svoju fotografiju u online natjecanje za određenu nagradu. Netko je ostavio vrlo ružan komentar ispod tvoje slike. Što ćeš učiniti?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Zamoliti roditelja ili stariju osobu od povjerenja da ti pomogne prijaviti komentar.");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Odmah uzvratiti ružnim komentarom");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Zamoliti prijatelje da napadnu tu osobu ružnim porukama");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Obrisati fotografiju");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Najbolji prijatelj ti je dao svoju lozinku i zatim napisao/la: „Ako si dobar prijatelj podijelit ćeš i ti svoju lozinku sa mnom?“ Što učiniti?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Reći kako ne možeš dijeliti svoju lozinku s drugima jer je ona samo tvoja te dati activity_savjet prijatelju/prijateljici da ne dijeli lozinku s drugima");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Odmah poslati svoju lozinku");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Dati lažnu lozinku");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Dati lozinku od profila drugog prijatelja");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Istražuješ podatke za referat za školu. Datum koji si pronašao nije isti za onaj koji ti tvoj prijatelj ili prijateljica tvrdi da je točan. Što ćeš učiniti?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Provjerit ću izvor informacija prijatelja te na par drugih web stranica kako bi potvrdio istinitost. Mogu se obratiti i starijoj osobi s malo više iskustva.");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Odmah ću napisati datum koji ti je prijatelj predložio.");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Sam ćeš odlučiti koji ti se datum više sviđa");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Web stranica mora biti u pravu. Ako je na internetu onda je sigurno stručno.");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Netko koga poznaješ samo online te zamolio da se nađete u parku gdje često budeš s prijateljima. Što ćeš učiniti?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Odmah reći roditeljima ili starijoj osobi od povjerenja.");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Poslati poruku da ćete se naći poslije škole i povesti prijatelje.");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Dogovoriti sastanak na drugoj lokaciji");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Naći se s njim u parku, ipak ima puno ljudi pa si siguran/n");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Kome je potrebno razvijanje medijske pismenosti?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Djeci, mladima i odraslima");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Mobilnim uređajima");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Samo starim ljudima");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Kućanskim aparatima");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Što od navedenog ne trebaš raditi kako bi spriječio nasilje putem interneta?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Uzvratiti istom mjerom i pokazati tko je glavni");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Obavijestiti roditelje ili školskog pedagoga/psihologa");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Razgovarati sa žrtvom, savjetovati da ne odgovara na bilo kakve sumnjive poruke");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Prijaviti slučaj administratoru internetske stranice");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Što je u kompjuterskom žargonu predstavlja oblak (engl. cloud)?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Virtualni prostor na kojem spremamo lične podatke i datoteke");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Granica između Zemlje i svemira");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Bijela nakupina koda iz koje pada internetska kiša");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nakupina programskih plinova");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Reklame za proizvode koji nas ne zanimaju a dobivamo ih u e-sandučiće nazivamo:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Spam");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Gmail");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Google");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Internet");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Svoje aplikacije možemo zaštititi:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Programom za zaštitu protiv virusa i zloćudnih programa");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Otkrivanjem svojih osobnih podataka na internetu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Otvaranjem sumnjivih e-mail priloga");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Instaliranjem raznih programa sa sumnjivih stranica");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Kako spriječiti trajno gubljenje podataka u slučaju napada?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Kontinuirano održavanje jedne ili više sigurnosnih kopija barem najbitnijih podataka");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Držati podatke u banci");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Čuvati podatke ispod madraca");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Kremom protiv gubljenja podataka");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Koja je svrha vatrozida (firewall)?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Služi kao prepreka između poznate i nepoznate mreže te dopušta ili zabranjuje promet između njih");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Da zapali zidove oko kompjutera");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Da se napadaču zapali kompjuter");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Da ugrije sobu");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Programi koji mogu prepoznati zloćudne programe i zaustaviti njihove aktivnosti nazivaju se:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Antivirusni programi, Antispyware programi, Antimalware programi");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Microsoft Word");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Program za crtanje Paint");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Kalkulator");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Za geografski udaljene korisnike, sigurnu komunikaciju s mrežom omogućit će:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("VPN, virtualna privatna mreža");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Planinska mreža");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Vulkanska mreža");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Susjedova mreža");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Dobio/la si email u kojemu te netko traži osobne podatke. Što učiniti?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Nikada nemoj davati svoje osobne podatke, pogotovo ne na email zahtjeve stranaca");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Pitati ih prvo za njihove osobne podatke");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Poslati fotografiju osobnih podataka (npr. Osobne iskaznice)");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Poslati osobne podatke");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Prijatelj je ostao prijavljen na društvenoj mreži na javnom školskom računalu. Što učiniti?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Odjaviti ga, javiti mu i preporučiti promjenu lozinke");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Javljati se drugim osobama s njegovog profila");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Objaviti podrugljive poruke");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Samostalno izmijeniti lozinku i onemogućiti mu korištenje profila");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Što učiniti ako sumnjamo u valjanost informacija stranice?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Provjeriti informaciju na više mjesta ili pitati roditelje ili nastavnike za activity_savjet");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Koristiti informaciju bez provjere valjanosti");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Unajmiti privatnog detektiva da istraži stranicu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Vjerovati svemu što piše na internetu");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Zašto odmah možemo zaključiti da se kod emailova arapskih prinčeva i dobitaka na lutriji radi o phishingu?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Traže da primatelj emaila pošalje svoje osobne podatke na adresu pošiljatelja i često sadrže rečenice loše prevedene na engleski jezik.");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ne radi se o phishingu, stvarno smo dobili na lutriji");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ne znamo dok ne probamo");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Radi se o velikim novcima, vrijedi riskirati");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Napadači svojim programima ciljaju na sljedeće podatke svojih žrtava:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Ime korisnika, broj kreditnih kartica, lozinke s kojima se mogu prijaviti kao korisnik");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ime kućnog ljubimca, veličina patika");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Korisnikove hobije");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Korisnikovu omiljenu boju");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Igrajući igricu s drugim ljudima, jedna osoba vas počne vrijeđati. Što učiniti?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Ostati smiren i pitati što je izazvalo uzrujanost; ako je osoba nerazumna, napustiti igru i izbjeći dodatno provociranje te prijaviti osobu vlasnicima igre");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Provocirati osobu kako ne zna igrati");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Hvaliti se kako ste bolji u igri od te osobe");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Uzvratiti istom ili većom mjerom");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Kako bi izbjegli situaciju da nam sigurnosne kopije podataka sadrže virus, trebamo:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Prije arhiviranja i snimanja sigurnosne kopije sadržaj provjeriti antivirusnim programom");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Sadržaj staviti na USB, pa s USB-a na drugo računalo");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Sadržaj staviti na CD pa ga obrisati vlažnim maramicama");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ne smiju se raditi sigurnosne kopije");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("'Mreža svih mreža' je popularan opis za:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Internet");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ribarska mreža");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Paukova mreža");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Telefonska mreža");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Je li preporučljivo automatsko ažuriranje operativnog sustava?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Da, kako bi se smanjila mogućnost zaraze kompjutera malverom");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nije, automatsko ažuriranje ne valja");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ažurirati se može samo manualno");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ne treba ažurirati operativni sustav");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Socijalnim inženjeringom manipulira se:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Ljudima");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Vjevericama");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Mobitelima");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Vatrom i ledom");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Zašto se ne preporučuje plaćanje otkupnine autorima ransomware-a?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Time financiramo kriminalne skupine i ne sprječavamo ih da nas ili druge opet napadnu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Novce treba štedjeti");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Novci mogu pokupiti virus");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Za te novce se može kupiti novi kompjuter");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Što ne spada u društvene medije?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Malware");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Instagram");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Facebook");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Twitter");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Bežična mreža je dobra ukoliko koristimo:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("WPA, WPA2 i WPA3 standarde enkripcije");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("mp3");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("mp4");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Bežična mreža nije nikad dobra");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Internet kupovinu treba obavljati:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Samo na provjerenim kompjuterima");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("S javnog kompjutera u kafiću");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Sa zaraženog kompjutera");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("S pozivom internet poslužitelju da im kažete popis stvari koje vam treba kupiti");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Skype je jedan od popularnih programa koji nam omogućuju:");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Razmjenu slike i glasa u realnom vremenu preko interneta");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Sigurno uzlijetanje aviona");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Besplatno skidanje filmova");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Meteorološke prognoze");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Netko me ucjenjuje s osjetljivim fotografijama, što učiniti?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Obratiti se roditeljima, nastavnicima ili Centru za sigurni internet kako bi pomogli");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ignorirati ucjenu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Platiti da prestane ucjenjivanje");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Prijetiti ucjenjivaču da ste profesionalni haker");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Koja se od navedenih lozinki čini najsigurnijom?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("$1gurn@L0z1Nka");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("teskalozinka1");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("12345");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("nesigurnalozinka");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Upoznao/la si novu osobu preko interneta. Što treba uzeti u obzir kod izmjenjivanja privatnih podataka?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Moguće je da se osoba lažno predstavlja i treba izbjeći davanje osjetljivih podataka dok niste sigurni u identitet druge osobe");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Osoba se potrudila upoznati te i ne moraš se brinuti oko sigurnosti svojih podataka");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Prvo izmijeniti fotografije, a onda ostale podatke");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nema razloga da se neko lažno predstavlja");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Smijem li pristupati svim sadržajima na internetu?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Ne, postoje mjesta na internetu koja su neprimjerena ili opasna ili mogu naštetiti mom kompjuteru");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ako se nešto dogodi, ugasit ću kompjuter");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Da, nema razloga za brigu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ako mogu drugi, mogu i ja");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Kojim aplikacijama na kompjuteru trebamo dati dozvolu za izvršavanje?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Samo onim koje smo željeli pokrenuti i za koje znamo što rade");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Sumnjivim aplikacijama čudnih imena");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Svim aplikacijama za koje iskoči upit");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Nijednoj aplikaciji");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Znamo osobu koja je napravila profil u ime neke poznate osobe i predstavlja se kao ta osoba. Što učiniti?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("Obavijestiti odraslu osobu i prijaviti lažni profil");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Javiti se lažnom profilu");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Dobra ideja, također napraviti profil u ime neke poznate osobe i malo se zabaviti");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("Ništa, nije vaš problem");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje
        p = new KvizPitanje();
        p.setVrsta("razredna");
        p.setTekst("Koja je dobna granica za registraciju na medijima kao što su Facebook, Instagram i Youtube?");
        o = new KvizOdgovor();
        o.setTocno(true);
        o.setTekst("13 godina");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("21 godina");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("16 godina");
        p.getOdgovori().add(o);
        o = new KvizOdgovor();
        o.setTocno(false);
        o.setTekst("18 godina");
        p.getOdgovori().add(o);
        pitanja.add(p);
// gotovo pitanje

        return pitanja;
    }

}
